#!/usr/bin/env bash
set -euo pipefail
compile() {
  node ljc.js -o "$1".js "$1".lj
}
set -x
compile Data/Bool
compile Data/Function
compile Data/List
compile Data/Maybe
compile Data/Tuple
compile Data/Unit
compile Lolo/Digits
compile Lolo/Parse
compile Lolo/Random
