#!/usr/bin/env bash
set -euo pipefail
echorun() {
  echo "$@"
  "$@"
}
compile() {
  lastarg=${!#}
  otherargs=("${@:1:$#-1}")
  echorun node ljc.js "${otherargs[@]}" -o "$lastarg".js "$lastarg".lj
}
compile Data/Bool
compile Data/Function
compile Data/JString
compile Data/List
compile Data/Maybe
compile Data/Tuple
compile Data/Unit
compile Lolo/Digits
compile Lolo/Parse
compile Lolo/Random
compile Lolo/Tap
compile -m test/lj/src/Data/List/Append
compile -m test/lj/src/Data/List/Replicate
compile -m test/lj/src/Lolo/Random/Test
